-- Seed page_content_blocks with the current hardcoded text from each marketing page.
-- This ensures the hub editor shows real current copy immediately once applied.
-- Uses WHERE NOT EXISTS idempotent insert so it's safe to re-run.

-- HOME page
INSERT INTO page_content_blocks (page_slug, block_key, label, content)
SELECT 'home', v.block_key, v.label, v.content
FROM (VALUES
  ('hero_tag',                  'Hero — location tag',                                       'Worthing, West Sussex'),
  ('hero_line_1',               'Hero — line 1',                                             'Exercise'),
  ('hero_line_2',               'Hero — line 2',                                             'for Health'),
  ('hero_line_3',               'Hero — line 3',                                             'Conditions'),
  ('hero_loc',                  'Hero — location line',                                      'Private one-to-one personal training in Worthing'),
  ('hero_subheading',           'Hero — subheading',                                         'Specialist training for people with health conditions, complex needs, and anyone the mainstream fitness industry has overlooked. Every session adapts to how you feel that day — because the same plan can be right one week and wrong the next. GP-referred clients welcome.'),
  ('hero_btn_primary',          'Hero — primary CTA button',                                 'Book a Free Consultation'),
  ('hero_btn_secondary',        'Hero — secondary CTA link',                                 'Find Out How It Works'),
  ('badge_title',               'Hero — badge title',                                        'Level 4 Qualified'),
  ('badge_sub',                 'Hero — badge subtitle',                                     'The highest PT qualification in the UK — plus cancer rehab and exercise referral'),
  ('ticker_1',                  'Ticker — item 1',                                           'Level 4 Personal Trainer'),
  ('ticker_2',                  'Ticker — item 2',                                           'Cancer Rehabilitation Specialist'),
  ('ticker_3',                  'Ticker — item 3',                                           'Exercise Referral Specialist'),
  ('ticker_4',                  'Ticker — item 4',                                           'GP-Referred Clients Welcome'),
  ('ticker_5',                  'Ticker — item 5',                                           'Private One-to-One Studio'),
  ('ticker_6',                  'Ticker — item 6',                                           'Based in Worthing'),
  ('why_tag',                   'Why — section tag',                                         'Why Eternal Fitness'),
  ('why_body',                  'Why — body paragraph',                                      'Esther Fair is a Level 4 personal trainer, Exercise Referral Specialist, and Cancer Rehabilitation Specialist based in Worthing. She specialises in rehabilitation and recovery training for cancer treatment survivors, chronic health conditions, post-surgery recovery, disabilities, and anyone with complex medical needs who has been overlooked by mainstream fitness.'),
  ('why_feat_1_title',          'Why — feature 1 title',                                     'Specialist in complex health conditions'),
  ('why_feat_1_desc',           'Why — feature 1 description',                               'Cancer rehabilitation, chronic illness, neurological conditions, post-surgical recovery, mobility limitations.'),
  ('why_feat_2_title',          'Why — feature 2 title',                                     'Strength and mobility for real life'),
  ('why_feat_2_desc',           'Why — feature 2 description',                               'Building functional strength that improves everyday movement, independence, and confidence.'),
  ('why_feat_3_title',          'Why — feature 3 title',                                     'Calm, private, one-to-one training'),
  ('why_feat_3_desc',           'Why — feature 3 description',                               'A private studio with no gym floor, no other clients, no pressure to look or perform.'),
  ('who_tag',                   'Who — section tag',                                         'Who This Is For'),
  ('who_body',                  'Who — body paragraph',                                      'I have worked with clients managing cancer, chronic illness, disability, visual impairment, neurological conditions, and complex mobility issues. I am here for the people other trainers cannot help.'),
  ('who_card_1_title',          'Who — card 1 title',                                        'People managing health conditions, disability, or injury'),
  ('who_card_1_desc',           'Who — card 1 description',                                  'Cancer rehabilitation. Chronic illness. Neurological conditions. Post-surgical recovery. Extreme mobility limitations. Level 4 qualified and exercise referral trained — I know how to work safely and effectively with complex needs.'),
  ('who_card_1_link',           'Who — card 1 link label',                                   'See Specialist Areas'),
  ('who_card_2_title',          'Who — card 2 title',                                        'People who have never felt welcome in fitness spaces'),
  ('who_card_2_desc',           'Who — card 2 description',                                  'Whether you are a complete beginner, have had negative experiences elsewhere, or simply find gyms intimidating — the private, one-to-one format at Eternal Fitness is designed to feel completely different. No dress code, no weigh-in, no comparison to anyone else.'),
  ('approach_tag',              'Approach — section tag',                                    'The Approach'),
  ('approach_body',             'Approach — body paragraph',                                 'I am always watching and always adapting. Every session starts with a check-in — energy levels, pain, sleep, what''s changed since last week. The plan for that day is set then, not before you walk through the door.'),
  ('approach_step_1_title',     'Approach — step 1 title',                                   'Every session adapts to how you feel that day'),
  ('approach_step_1_desc',      'Approach — step 1 description',                             'Fatigue, flares, bad nights, medication changes — I notice and adjust without drawing attention to it. You always leave feeling you''ve done something worthwhile.'),
  ('approach_step_2_title',     'Approach — step 2 title',                                   'Private 1-to-1 studio — no gym floor'),
  ('approach_step_2_desc',      'Approach — step 2 description',                             'No other clients. No performance pressure. No dress code. A calm, private space where the only focus is you and what you need today.'),
  ('approach_step_3_title',     'Approach — step 3 title',                                   'Functional progress — not transformation'),
  ('approach_step_3_desc',      'Approach — step 3 description',                             'Climbing stairs with less pain. Better sleep. More energy. Walking further. These are the outcomes that matter to the people I work with — and they''re the ones I build towards.'),
  ('approach_box_1_title',      'Approach — qualification box 1 title',                      'Level 4 qualified — the highest mainstream PT certification in the UK'),
  ('approach_box_1_desc',       'Approach — qualification box 1 description',                'Exercise Referral Specialist and Cancer Rehabilitation Specialist. Trained to work with GP-referred clients, chronic conditions, post-treatment recovery, and complex medical needs. Most PTs are not qualified for this work.'),
  ('approach_box_2_title',      'Approach — qualification box 2 title',                      'No weigh-ins. No judgement. No agenda.'),
  ('approach_box_2_desc',       'Approach — qualification box 2 description',                'No before-and-after framing, no expectations about what fitness should look like. The goal is what matters to you — whether that''s managing pain, regaining independence, or simply moving with more confidence.'),
  ('spec_tag',                  'Specialist — section tag',                                  'Specialist Areas'),
  ('spec_heading',              'Specialist — heading',                                      'Who I Work With'),
  ('spec_body',                 'Specialist — body paragraph',                               'Cancer rehabilitation (active treatment, in remission, post-surgery). Chronic health conditions (fibromyalgia, ME/CFS, autoimmune, diabetes, heart conditions). Disability and adaptive training. Neurological conditions. GP-referred programmes. If your situation is not listed — please still get in touch. The answer is almost always yes.'),
  ('spec_card_1_title',         'Specialist — card 1 title',                                 'Cancer Rehabilitation'),
  ('spec_card_1_desc',          'Specialist — card 1 description',                           'Specialist support during treatment, in remission, and post-surgery.'),
  ('spec_card_2_title',         'Specialist — card 2 title',                                 'Exercise for Health'),
  ('spec_card_2_desc',          'Specialist — card 2 description',                           'Blood pressure, diabetes, bone strength, mobility and more — exercise referral specialists.'),
  ('spec_card_3_title',         'Specialist — card 3 title',                                 'Visual Impairment'),
  ('spec_card_3_desc',          'Specialist — card 3 description',                           'Adapted training for people who are blind or partially sighted.'),
  ('testimonial_1',             'Testimonials — quote 1',                                    'I was so nervous about starting, but from the first session Esther put me at ease. She listened, adapted everything to my condition, and I have never felt stronger or more confident in my own body.'),
  ('testimonial_2',             'Testimonials — quote 2',                                    E'\u201CAs someone who has dealt with chronic pain for years, I was sceptical that exercise could help. The personalised approach at Eternal Fitness has genuinely changed my quality of life. I cannot recommend it enough.\u201D'),
  ('testimonial_heading',       'Testimonials — heading',                                    'Client Stories'),
  ('testimonial_body',          'Testimonials — body paragraph',                             'Progress looks different for everyone. For some it is lifting more, for others it is walking without pain, sleeping better, or simply feeling at home in their own body.'),
  ('testimonial_link',          'Testimonials — link label',                                 'Read the FAQs'),
  ('cta_tag',                   'CTA — section tag',                                         'Free Consultation'),
  ('cta_heading',               'CTA — heading',                                             'Ready to find out if this is right for you?'),
  ('cta_body',                  'CTA — body paragraph',                                      'The first conversation is free, with no commitment. I work with a small number of clients at a time — so every person gets my full attention.'),
  ('cta_btn_primary',           'CTA — primary button',                                      'Book a Free Consultation'),
  ('cta_btn_secondary',         'CTA — secondary button',                                    'Call: 07517 658 128')
) AS v(block_key, label, content)
WHERE NOT EXISTS (SELECT 1 FROM page_content_blocks WHERE page_slug = 'home' AND block_key = v.block_key);

-- ABOUT page
INSERT INTO page_content_blocks (page_slug, block_key, label, content)
SELECT 'about', v.block_key, v.label, v.content
FROM (VALUES
  ('hero_eyebrow',              'Hero — eyebrow',                                            'About Esther'),
  ('hero_heading',              'Hero — heading',                                            'About Esther Fair — Cancer Rehabilitation Specialist'),
  ('hero_subhead',              'Hero — subheading',                                         'Level 4 Personal Trainer. Cancer Rehabilitation Specialist. Exercise Referral Specialist. I know first-hand what it feels like to start from zero.'),
  ('hero_btn_primary',          'Hero — primary CTA button',                                 'Book a Free Consultation'),
  ('hero_btn_secondary',        'Hero — secondary CTA link',                                 'My Story'),
  ('badge_label',               'Hero — badge label',                                        'Level 4 Qualified'),
  ('badge_sublabel',            'Hero — badge sublabel',                                     'Cancer Rehab & Exercise Referral'),
  ('story_eyebrow',             'Story — eyebrow',                                           'My Story'),
  ('story_heading',             'Story — heading',                                           'I Have Been Where You Are'),
  ('story_p1',                  'Story — paragraph 1',                                       'I did not come to fitness from a place of confidence. There was a time when exercise felt inaccessible, intimidating, and simply not something that was meant for me. When that changed, it changed everything — my health, my recovery, my sense of what my body was capable of.'),
  ('story_p2',                  'Story — paragraph 2',                                       'That experience is the reason I became a personal trainer. Not to help people lose weight or achieve an aesthetic ideal — but to help people rehabilitate, recover, and feel stronger, more capable, and more functional in their own bodies, regardless of their health conditions or limitations.'),
  ('story_p3',                  'Story — paragraph 3',                                       'I qualified to Level 4 — the highest personal training qualification in the UK — and went further with specialist certifications in Cancer Rehabilitation and Exercise Referral. I specifically sought these qualifications to work with people who have more complex medical needs: cancer treatment survivors, those with chronic health conditions, post-surgical recovery, disabilities, and clients whose health situations have led other trainers to say they cannot help. Those are exactly the clients I am here for.'),
  ('quals_eyebrow',             'Qualifications — eyebrow',                                  'Qualifications'),
  ('quals_heading',             'Qualifications — heading',                                  'Qualified to Help Where Others Cannot'),
  ('quals_intro',               'Qualifications — intro',                                    'Most personal trainers hold a Level 3 qualification. I hold Level 4 — alongside specialist certifications that are rare in any fitness setting.'),
  ('qual_1_title',              'Qualification 1 — title',                                   'Level 4 Personal Trainer'),
  ('qual_1_desc',               'Qualification 1 — description',                             'The highest level of personal training qualification in the UK — above the Level 3 held by most personal trainers. Registered with a recognised UK fitness body.'),
  ('qual_2_title',              'Qualification 2 — title',                                   'Exercise Referral Specialist'),
  ('qual_2_desc',               'Qualification 2 — description',                             'Qualified to work with GP-referred clients and those with clinical conditions requiring adapted exercise programmes.'),
  ('qual_3_title',              'Qualification 3 — title',                                   'Cancer Rehabilitation'),
  ('qual_3_desc',               'Qualification 3 — description',                             'Specialist training to support people through cancer treatment and recovery, including those currently in active treatment.'),
  ('exp_eyebrow',               'Experience — eyebrow',                                      'Experience'),
  ('exp_heading',               'Experience — heading',                                      'Experience Across the Full Range of Human Complexity'),
  ('exp_p1',                    'Experience — paragraph 1',                                  'Over the years, I have worked with clients that most personal trainers would not know how to support — cancer treatment survivors and people in recovery, people managing serious chronic health conditions (fibromyalgia, ME/CFS, autoimmune diseases, heart conditions), people in post-surgical or post-fracture rehabilitation, people with physical disabilities and mobility limitations, clients with significant visual impairment, people with neurological conditions (Parkinson''s, MS, stroke recovery), and anyone whose health situation doesn''t fit into mainstream fitness templates.'),
  ('exp_p2',                    'Experience — paragraph 2',                                  'I mention this not to boast, but because you might be wondering whether your situation is too complicated, too medically complex, or too much. It almost certainly is not. My Cancer Rehabilitation and Exercise Referral certifications equip me to work alongside your GP, specialist, and healthcare team. Every programme is built from scratch — with complete medical awareness and respect for whatever your body, health conditions, recovery status, or history looks like.'),
  ('exp_callout_title',         'Experience — callout title',                                'Not sure if you qualify?'),
  ('phil_eyebrow',              'Philosophy — eyebrow',                                      'Philosophy'),
  ('phil_heading',              'Philosophy — heading',                                      'The Philosophy'),
  ('phil_p1',                   'Philosophy — paragraph 1',                                  'Eternal Fitness is not a weight loss service. It is not about transforming your body into something it is not. It is about rehabilitation and recovery — finding out what your body is capable of right now, with all the health conditions, medications, limitations, and recovery status it is currently dealing with — and building steadily from there.'),
  ('phil_p2',                   'Philosophy — paragraph 2',                                  'The goal is not a six-week result. It is returning to activities after cancer treatment. Being able to move with less pain. Having better fatigue management. Managing your chronic condition without fear. Recovering full function after injury. Climbing stairs. Walking further. Moving through life with more ease, capability, and confidence than before. That takes time, consistency, and working with someone who genuinely understands medical complexity and adjusts when your health or capacity changes. That is what I do.'),
  ('phil_callout_title',        'Philosophy — callout title',                                'More Than a Workout'),
  ('phil_callout_body',         'Philosophy — callout body',                                 'No weigh-ins. No before-and-after photos. No pressure to look a certain way. Just steady, meaningful progress — measured against your own baseline, not anyone else''s.'),
  ('studio_eyebrow',            'Studio — eyebrow',                                          'Studio'),
  ('studio_heading',            'Studio — heading',                                          'A Private Space in Worthing'),
  ('studio_intro',              'Studio — intro',                                            'Sessions take place in a small, private, fully equipped studio. No public gym floor. No other clients watching. No ambient pressure of what anyone else around you is doing.'),
  ('studio_card_1_title',       'Studio — card 1 title',                                     'Designed for All Abilities'),
  ('studio_card_1_desc',        'Studio — card 1 description',                               'Studio set up for disabilities, mobility limitations, and complex health needs — with equipment chosen for functional recovery, not performance aesthetics.'),
  ('studio_card_2_title',       'Studio — card 2 title',                                     'Equipment That Serves You'),
  ('studio_card_2_desc',        'Studio — card 2 description',                               'Every piece is chosen to support rehabilitation, recovery, and real-life movement. Resistance bands, mobility tools, and adaptive kit — nothing intimidating.'),
  ('studio_card_3_title',       'Studio — card 3 title',                                     'A Calm Environment'),
  ('studio_card_3_desc',        'Studio — card 3 description',                               'No gym floor, no other clients watching, no ambient pressure. Quiet, private, one-to-one sessions — because recovery needs calm, not noise.'),
  ('long_eyebrow',              'Long-Term — eyebrow',                                       'Long-Term Progress'),
  ('long_heading',              'Long-Term — heading',                                       'Why the Long-Term Approach Matters'),
  ('long_intro',                'Long-Term — intro',                                         'Quick fixes do not work. Sustainable change does — and Eternal Fitness is built around that belief.'),
  ('long_card_1_title',         'Long-Term — card 1 title',                                  'The Power of Consistency'),
  ('long_card_1_desc',          'Long-Term — card 1 description',                            'Small, steady actions repeated over time create lasting physical and mental change — without extremes.'),
  ('long_card_2_title',         'Long-Term — card 2 title',                                  'Adapting When Things Change'),
  ('long_card_2_desc',          'Long-Term — card 2 description',                            'Life and health are unpredictable. Your programme adapts with you, so progress never stops — it just looks different.'),
  ('long_card_3_title',         'Long-Term — card 3 title',                                  'Real Outcomes, Not Aesthetics'),
  ('long_card_3_desc',          'Long-Term — card 3 description',                            'Stronger, more capable, more comfortable in your body. These are the results that actually matter.'),
  ('cta_heading',               'CTA — heading',                                             'Ready to find out if this is right for you?'),
  ('cta_body',                  'CTA — body paragraph',                                      'The first conversation is free, with no commitment. I work with a small number of clients at a time — so every person gets my full attention.'),
  ('cta_btn_primary',           'CTA — primary button',                                      'Book a Free Consultation'),
  ('cta_btn_secondary',         'CTA — secondary button',                                    'Call: 07517 658 128')
) AS v(block_key, label, content)
WHERE NOT EXISTS (SELECT 1 FROM page_content_blocks WHERE page_slug = 'about' AND block_key = v.block_key);

-- PERSONAL TRAINING page
INSERT INTO page_content_blocks (page_slug, block_key, label, content)
SELECT 'personal-training', v.block_key, v.label, v.content
FROM (VALUES
  ('hero_eyebrow',              'Hero — eyebrow',                                            'Personal Training'),
  ('hero_heading',              'Hero — heading',                                            'Cancer Rehabilitation and Recovery Training in Worthing'),
  ('hero_subhead',              'Hero — subheading',                                         'Private one-to-one sessions with a Cancer Rehabilitation Specialist and Exercise Referral Specialist (Level 4 qualified). Whether you are in cancer treatment, post-surgery recovery, managing a chronic condition, living with a disability, or have complex medical needs — there is a specialist programme here for you.'),
  ('hero_btn_primary',          'Hero — primary CTA button',                                 'Book a Free Consultation'),
  ('hero_btn_secondary',        'Hero — secondary CTA link',                                 'What Sessions Involve'),
  ('badge_label',               'Hero — badge label',                                        'Cancer Rehab & Exercise Referral'),
  ('what_eyebrow',              'What to Expect — eyebrow',                                  'What to Expect'),
  ('what_heading',              'What to Expect — heading',                                  'This Is Not Like Other Personal Training'),
  ('what_p1',                   'What to Expect — paragraph 1',                              'Personal training at Eternal Fitness is not about pushing harder, going faster, or doing more. It is about rehabilitation, recovery, and what your body needs right now — whether managing a health condition, recovering from cancer treatment, or living with a disability — and building a sustainable programme around that. Sessions are private, one-to-one, and held in a small studio in Worthing where there is no gym floor, no other clients watching, and no comparison to anyone else.'),
  ('what_p2',                   'What to Expect — paragraph 2',                              'My specialist training in cancer rehabilitation and exercise referral means I am trained to adapt to medical conditions, medication side-effects, fatigue cycles, and variable capacity. I work within your GP''s or specialist''s guidance. I do not guess — I ask, I listen, and I adjust every session based on your body''s actual needs that day.'),
  ('spec_eyebrow',              'Specialist Areas — eyebrow',                                'Specialist Areas'),
  ('spec_heading',              'Specialist Areas — heading',                                'Who I Work With'),
  ('spec_intro',                'Specialist Areas — intro',                                  'I specialise in working with people who have been underserved by mainstream fitness. If your situation is not listed here, please still get in touch — the answer is almost always yes.'),
  ('spec_panel_eyebrow',        'Specialist Areas — panel eyebrow',                          'Specialist areas'),
  ('area_1_title',              'Specialist area 1 — title',                                 'Cancer & cancer rehabilitation'),
  ('area_1_desc',               'Specialist area 1 — description',                           'During active treatment, in remission, or post-surgery. I am qualified in cancer rehabilitation and adapt to wherever you are in your journey.'),
  ('area_2_title',              'Specialist area 2 — title',                                 'Chronic health conditions'),
  ('area_2_desc',               'Specialist area 2 — description',                           'Including autoimmune conditions, fibromyalgia, ME/CFS, heart conditions, diabetes, and more. Every session adapts to what your body can manage that day.'),
  ('area_3_title',              'Specialist area 3 — title',                                 'Disability & adaptive training'),
  ('area_3_desc',               'Specialist area 3 — description',                           'Physical disabilities, significant mobility limitations, and sensory impairments including visual impairment. Programmes are built around your body, not a template.'),
  ('area_4_title',              'Specialist area 4 — title',                                 'GP-referred exercise'),
  ('area_4_desc',               'Specialist area 4 — description',                           'I am qualified in exercise referral and experienced in working alongside medical guidance from GPs and healthcare teams.'),
  ('area_5_title',              'Specialist area 5 — title',                                 'Injury recovery & rehabilitation'),
  ('area_5_desc',               'Specialist area 5 — description',                           'Post-surgical, post-fracture, and musculoskeletal conditions. I work within the guidance of your physiotherapist or consultant.'),
  ('area_6_title',              'Specialist area 6 — title',                                 'Neurological conditions'),
  ('area_6_desc',               'Specialist area 6 — description',                           'Including Parkinson''s, MS, stroke recovery, and acquired brain injury. Gentle, progressive, and always adapted.'),
  ('spec_cta_learn',            'Specialist Areas — CTA learn more',                         'Learn more'),
  ('spec_cta_book',             'Specialist Areas — CTA book consultation',                  'Book a consultation'),
  ('focus_eyebrow',             'What I Work On — eyebrow',                                  'What I Work On'),
  ('focus_heading',             'What I Work On — heading',                                  'Recovery and Rehabilitation for Real Life'),
  ('focus_intro',               'What I Work On — intro',                                    'The focus is functional rehabilitation — building strength, mobility, endurance, and capability for real life during and after health conditions. Not aesthetics. Not performance metrics. Real outcomes: returning to activities after cancer treatment, climbing stairs without pain, managing fatigue, walking further, recovering independence, sleeping better, regaining confidence in your own body.'),
  ('focus_1_title',             'Focus card 1 — title',                                      'Mobility and joint health'),
  ('focus_1_desc',              'Focus card 1 — description',                                'Improving range of motion, reducing stiffness, and moving with less effort and pain day-to-day.'),
  ('focus_2_title',             'Focus card 2 — title',                                      'Functional strength'),
  ('focus_2_desc',              'Focus card 2 — description',                                'Building practical strength for real life — carrying shopping, climbing stairs, getting up from the floor.'),
  ('focus_3_title',             'Focus card 3 — title',                                      'Balance and stability'),
  ('focus_3_desc',              'Focus card 3 — description',                                'Reducing fall risk and building the physical confidence to move through your environment safely.'),
  ('focus_4_title',             'Focus card 4 — title',                                      'Fatigue management'),
  ('focus_4_desc',              'Focus card 4 — description',                                'Learning how to train effectively when energy levels are variable or unpredictable — a common challenge with many health conditions.'),
  ('process_eyebrow',           'How It Works — eyebrow',                                    'The Process'),
  ('process_heading',           'How It Works — heading',                                    'How It Works'),
  ('step_1_title',              'Step 1 — title',                                            'Free Consultation'),
  ('step_1_desc',               'Step 1 — description',                                      'A relaxed 30-minute conversation with me about your goals, health history, and what has and has not worked before. No pressure, no commitment.'),
  ('step_2_title',              'Step 2 — title',                                            'Movement Assessment'),
  ('step_2_desc',               'Step 2 — description',                                      'I check your current mobility, strength, and any limitations before any programme begins — so training starts safely and clearly.'),
  ('step_3_title',              'Step 3 — title',                                            'Your Programme'),
  ('step_3_desc',               'Step 3 — description',                                      'A plan built entirely around your body and your life. Session structure, exercises, and intensity are all tailored specifically to you.'),
  ('step_4_title',              'Step 4 — title',                                            'Ongoing Support'),
  ('step_4_desc',               'Step 4 — description',                                      'I adjust your programme as your health and capacity change — keeping training sustainable, realistic, and aligned with where you are.'),
  ('pages_eyebrow',             'Specialist Pages — eyebrow',                                'Specialist Pages'),
  ('pages_heading',             'Specialist Pages — heading',                                'Condition-Specific Training'),
  ('pages_intro',               'Specialist Pages — intro',                                  'Each of my specialist areas has a dedicated page with more detail about how I work with specific conditions.'),
  ('page_1_title',              'Specialist page 1 — title',                                 'Exercise for Health'),
  ('page_1_desc',               'Specialist page 1 — description',                           'Training for high blood pressure, type 2 diabetes, osteoporosis, COPD, heart conditions, chronic pain and more.'),
  ('page_2_title',              'Specialist page 2 — title',                                 'Cancer Rehabilitation'),
  ('page_2_desc',               'Specialist page 2 — description',                           'Training during active treatment, in remission, or post-surgery. Qualified and experienced in cancer rehabilitation.'),
  ('page_3_title',              'Specialist page 3 — title',                                 'Visual Impairment'),
  ('page_3_desc',               'Specialist page 3 — description',                           'Adapted training for people who are blind or partially sighted. Verbal instruction, consistent environment, tactile guidance.'),
  ('stat_1_label',              'Stat strip — item 1 label',                                 'Cancer rehab & exercise referral qualified'),
  ('stat_2_label',              'Stat strip — item 2 label',                                 'Private one-to-one sessions only'),
  ('stat_3_label',              'Stat strip — item 3 label',                                 'Free, no-pressure consultation'),
  ('stat_4_label',              'Stat strip — item 4 label',                                 'Private studio, West Sussex'),
  ('blog_eyebrow',              'Related Articles — eyebrow',                                'Learn More'),
  ('blog_heading',              'Related Articles — heading',                                'Related Articles'),
  ('blog_intro',                'Related Articles — intro',                                  'Read more about training with health conditions, recovery strategies, and what makes specialist personal training different.'),
  ('blog_link_label',           'Related Articles — link label',                             'Read article'),
  ('blog_btn',                  'Related Articles — button',                                 'View All Articles'),
  ('article_1_title',           'Related article 1 — title',                                 'Exercise & Illness'),
  ('article_1_desc',            'Related article 1 — description',                           'Understanding how to stay active during health challenges and what''s safe when managing chronic conditions.'),
  ('article_2_title',           'Related article 2 — title',                                 'Menopause & Exercise'),
  ('article_2_desc',            'Related article 2 — description',                           'How to train effectively through hormonal changes and manage strength, mobility, and energy during midlife transitions.'),
  ('article_3_title',           'Related article 3 — title',                                 'Resistance Training & Blood Pressure'),
  ('article_3_desc',            'Related article 3 — description',                           'Safety considerations for people managing cardiovascular health and how resistance training can be part of a healthy approach.'),
  ('cta_heading',               'CTA — heading',                                             'Ready to find out if this is right for you?'),
  ('cta_body',                  'CTA — body paragraph',                                      'The first conversation is free, with no commitment. I work with a small number of clients at a time — so every person gets my full attention.'),
  ('cta_btn_primary',           'CTA — primary button',                                      'Book a Free Consultation'),
  ('cta_btn_secondary',         'CTA — secondary button',                                    'Call: 07517 658 128')
) AS v(block_key, label, content)
WHERE NOT EXISTS (SELECT 1 FROM page_content_blocks WHERE page_slug = 'personal-training' AND block_key = v.block_key);

-- EXERCISE FOR HEALTH page
INSERT INTO page_content_blocks (page_slug, block_key, label, content)
SELECT 'exercise-for-health', v.block_key, v.label, v.content
FROM (VALUES
  ('hero_eyebrow',              'Hero — eyebrow',                                            'Exercise for Health'),
  ('hero_subhead',              'Hero — subheading',                                         'Exercise is one of the most evidence-based interventions for managing a wide range of health conditions. The key is having a qualified specialist who understands your condition and programmes safely around it — not a standard PT working outside their training.'),
  ('hero_btn_primary',          'Hero — primary CTA button',                                 'Book a Free Consultation'),
  ('hero_btn_secondary',        'Hero — secondary CTA link',                                 'See Conditions Covered'),
  ('badge_label',               'Hero — badge label',                                        'Exercise Referral Specialist'),
  ('approach_eyebrow',          'The Approach — eyebrow',                                    'The Approach'),
  ('approach_heading',          'The Approach — heading',                                    'Exercise for health is different from exercise for fitness'),
  ('approach_p1',               'The Approach — paragraph 1',                                'Think of it like seeing a physiotherapist rather than a personal trainer. The goal is not weight loss, not aesthetics, and not performance. The goal is health — managing your condition, building functional strength, improving quality of life.'),
  ('approach_p2',               'The Approach — paragraph 2',                                'I work the same way a physio or an osteopath does — targeting conditions, not demographics. Every session starts with a check-in. The plan for that day is set then, based on how you actually feel — not how you felt last week.'),
  ('approach_p3',               'The Approach — paragraph 3',                                'As a Level 4 Personal Trainer and Exercise Referral Specialist, I am qualified to work with clinical populations that a standard Level 3 PT is not trained for. That distinction matters.'),
  ('cond_eyebrow',              'Conditions Covered — eyebrow',                              'Conditions Covered'),
  ('cond_heading',              'Conditions Covered — heading',                              'Who I Work With'),
  ('cond_intro',                'Conditions Covered — intro',                                'If your condition is not listed here, please still get in touch. The answer is almost always yes.'),
  ('cond_panel_eyebrow',        'Conditions Covered — panel eyebrow',                        'Conditions covered'),
  ('cond_1_title',              'Condition 1 — title',                                       'High Blood Pressure'),
  ('cond_1_desc',               'Condition 1 — description',                                 'Exercise is one of the most effective ways to lower blood pressure — when it is done safely and progressively. I am qualified in exercise referral for hypertension.'),
  ('cond_2_title',              'Condition 2 — title',                                       'Type 2 Diabetes'),
  ('cond_2_desc',               'Condition 2 — description',                                 'Structured exercise improves insulin sensitivity and blood sugar management. Sessions are planned around your medication timing and monitoring needs.'),
  ('cond_3_title',              'Condition 3 — title',                                       'Bone Health & Osteoporosis'),
  ('cond_3_desc',               'Condition 3 — description',                                 'Weight-bearing and resistance exercise is clinically recommended to slow bone density loss and reduce fracture risk. Safe, load-managed progression.'),
  ('cond_4_title',              'Condition 4 — title',                                       'Visual Impairment'),
  ('cond_4_desc',               'Condition 4 — description',                                 'Adapted training for people who are blind or partially sighted. Sessions built around clear verbal instruction, consistent equipment placement, and a familiar environment.'),
  ('cond_5_title',              'Condition 5 — title',                                       'COPD & Breathing Conditions'),
  ('cond_5_desc',               'Condition 5 — description',                                 'Exercise is recommended for people with COPD to improve function and quality of life. Sessions respect breathing capacity and build gradually.'),
  ('cond_6_title',              'Condition 6 — title',                                       'Heart Conditions'),
  ('cond_6_desc',               'Condition 6 — description',                                 'Post-cardiac rehabilitation and ongoing heart condition management. I work within the guidance of your cardiologist or GP.'),
  ('cond_7_title',              'Condition 7 — title',                                       'Chronic Pain & Fibromyalgia'),
  ('cond_7_desc',               'Condition 7 — description',                                 'Gentle, progressive movement that works with pain rather than against it. Sessions adapt to your energy and pain levels on the day.'),
  ('cond_8_title',              'Condition 8 — title',                                       'Physical Disability & Adaptive Training'),
  ('cond_8_desc',               'Condition 8 — description',                                 'Exercise programmes built entirely around your body and your goals — not a template. Wheelchair users, amputees, and neurological conditions welcome.'),
  ('cond_cta_learn',            'Conditions — CTA learn more',                               'Learn more'),
  ('cond_cta_book',             'Conditions — CTA book consultation',                        'Book a consultation'),
  ('how_eyebrow',               'How It Works — eyebrow',                                    'How It Works'),
  ('how_heading',               'How It Works — heading',                                    'What to Expect from Your Sessions'),
  ('step_1_title',              'Step 1 — title',                                            'Free consultation first'),
  ('step_1_body',               'Step 1 — body',                                            'We start with a conversation — no commitment, no obligation. I want to understand your condition, your history, and your goals before we do anything else.'),
  ('step_2_title',              'Step 2 — title',                                            'Check-in at the start of every session'),
  ('step_2_body',               'Step 2 — body',                                            'How are you feeling today? Energy, pain, sleep, any changes. The session plan is finalised then — because what works one week may not be right the next.'),
  ('step_3_title',              'Step 3 — title',                                            'Progress that adapts to you'),
  ('step_3_body',               'Step 3 — body',                                            'There is no fixed template. Programmes are built around your body, your condition, and your goals — and adjusted as those things change.'),
  ('faq_eyebrow',               'FAQ — eyebrow',                                             'Common Questions'),
  ('faq_heading',               'FAQ — heading',                                             'Questions About Exercising With a Health Condition'),
  ('faq_intro',                 'FAQ — intro',                                               'If your question is not covered here, just ask — I would always rather you did.'),
  ('faq_1_title',               'FAQ 1 — question',                                          'Can I exercise if I have a health condition?'),
  ('faq_1_body',                'FAQ 1 — answer',                                            'In most cases, yes — and the evidence strongly supports it. Exercise is clinically recommended for a wide range of conditions. The key is having a qualified specialist who understands your specific condition and can programme safely around it.'),
  ('faq_2_title',               'FAQ 2 — question',                                          'Do I need a GP referral?'),
  ('faq_2_body',                'FAQ 2 — answer',                                            'No. A GP referral is welcome but not required. Many clients come independently. I will ask about your medical history and may recommend checking with your GP if there are specific contraindications to consider first.'),
  ('faq_3_title',               'FAQ 3 — question',                                          'How is this different from a regular personal trainer?'),
  ('faq_3_body',                'FAQ 3 — answer',                                            'A standard Level 3 PT is not trained to work with clinical populations. As a Level 4 Exercise Referral Specialist, I understand contraindicated exercises, medication effects, fatigue management, and how conditions affect capacity from one session to the next.'),
  ('faq_4_title',               'FAQ 4 — question',                                          'What if I am having a bad day when I come in?'),
  ('faq_4_body',                'FAQ 4 — answer',                                            'That is what the check-in is for. I adapt the session to how you actually feel — not how the plan says you should feel. You will always leave having done something genuinely useful, even on the difficult days.'),
  ('cta_heading',               'CTA — heading',                                             'Ready to find out if this is right for you?'),
  ('cta_body',                  'CTA — body paragraph',                                      'The first conversation is free, with no commitment. I work with a small number of clients at a time — so every person gets my full attention.'),
  ('cta_btn_primary',           'CTA — primary button',                                      'Book a Free Consultation'),
  ('cta_btn_secondary',         'CTA — secondary button',                                    'Call: 07517 658 128')
) AS v(block_key, label, content)
WHERE NOT EXISTS (SELECT 1 FROM page_content_blocks WHERE page_slug = 'exercise-for-health' AND block_key = v.block_key);

-- CANCER REHABILITATION page
INSERT INTO page_content_blocks (page_slug, block_key, label, content)
SELECT 'cancer-rehabilitation', v.block_key, v.label, v.content
FROM (VALUES
  ('hero_eyebrow',              'Hero — eyebrow',                                            'Cancer Rehabilitation'),
  ('hero_subhead',              'Hero — subheading',                                         'Specialist one-to-one support during treatment, in remission, and post-surgery. Exercise is now strongly evidenced as beneficial throughout the cancer journey — with the right guidance, at the right intensity, from someone qualified to provide it.'),
  ('hero_btn_primary',          'Hero — primary CTA button',                                 'Book a Free Consultation'),
  ('hero_btn_secondary',        'Hero — secondary CTA link',                                 'See Pricing'),
  ('badge_label',               'Hero — badge label',                                        'Cancer Rehab Specialist'),
  ('evidence_eyebrow',          'The Evidence — eyebrow',                                    'The Evidence'),
  ('evidence_heading',          'The Evidence — heading',                                    'Why exercise matters during the cancer journey'),
  ('evidence_p1',               'The Evidence — paragraph 1',                                'Exercise during and after cancer treatment is no longer considered risky — the evidence now strongly supports it. Research shows that appropriate exercise during chemotherapy is associated with reduced fatigue, better mood, improved immune function, and faster recovery.'),
  ('evidence_p2',               'The Evidence — paragraph 2',                                'After treatment, structured exercise has been shown to improve overall survival rates in some cancer types, reduce the risk of recurrence, and significantly improve quality of life.'),
  ('evidence_p3',               'The Evidence — paragraph 3',                                E'The qualifier is \u201Cappropriate.\u201D The intensity, type of exercise, and how it adapts to treatment side effects matters enormously \u2014 and that is where specialist training is essential.'),
  ('evidence_callout_title',    'The Evidence — callout title',                              'Cancer Rehabilitation Specialist qualification'),
  ('evidence_callout_body',     'The Evidence — callout body',                               'Trained at Level 4 to work with people during and after cancer treatment. This is a specialist qualification, not standard personal training.'),
  ('stages_eyebrow',            'Stages — eyebrow',                                          'When I Can Help'),
  ('stages_heading',            'Stages — heading',                                          'Support at Every Stage'),
  ('stage_1_title',             'Stage 1 — title',                                           'During active treatment'),
  ('stage_1_body',              'Stage 1 — body',                                            'Chemotherapy and radiotherapy significantly affect energy, immune function, and physical capacity — and those effects are unpredictable from week to week. Sessions during active treatment are lower intensity, shorter, and built around your current treatment schedule. Every session begins with a check-in.'),
  ('stage_2_title',             'Stage 2 — title',                                           'In remission'),
  ('stage_2_body',              'Stage 2 — body',                                            'Remission brings its own challenges — rebuilding fitness that has been lost, managing ongoing fatigue or side effects, and navigating the physical and emotional after-effects of treatment. Sessions progress gradually, respecting the timeline your body needs.'),
  ('stage_3_title',             'Stage 3 — title',                                           'Post-surgery'),
  ('stage_3_body',              'Stage 3 — body',                                            'Whether mastectomy, colostomy, lymph node removal, or another procedure — post-surgical return to exercise requires careful, staged progression. I work within the guidance of your surgical team and will not progress any movement without appropriate medical clearance.'),
  ('clin_eyebrow',              'Clinical Considerations — eyebrow',                         'Clinical Considerations'),
  ('clin_heading',              'Clinical Considerations — heading',                         'What I Know and How I Work'),
  ('cons_1_title',              'Consideration 1 — title',                                   'Cancer-related fatigue is different'),
  ('cons_1_body',               'Consideration 1 — body',                                    'Cancer-related fatigue (CRF) does not respond to rest the way ordinary tiredness does. It is physiologically distinct — and training must account for it. I will never push through CRF or interpret it as effort avoidance.'),
  ('cons_2_title',              'Consideration 2 — title',                                   'Lymphoedema awareness'),
  ('cons_2_body',               'Consideration 2 — body',                                    'For clients with or at risk of lymphoedema, I monitor for signs of swelling, avoid tight compression, and follow safe exercise guidelines. Exercise can actually help manage lymphoedema when programmed correctly.'),
  ('cons_3_title',              'Consideration 3 — title',                                   'Bone density'),
  ('cons_3_body',               'Consideration 3 — body',                                    'Some cancer treatments (particularly certain hormonal therapies) accelerate bone density loss. Weight-bearing and resistance exercise is clinically recommended — but load and progression must be managed carefully.'),
  ('cons_4_title',              'Consideration 4 — title',                                   'GP or oncologist sign-off'),
  ('cons_4_body',               'Consideration 4 — body',                                    'Before beginning any structured exercise programme during or shortly after treatment, I ask for GP or oncologist clearance. This is non-negotiable — not because I am being cautious, but because it is the right clinical standard.'),
  ('stat_1_label',              'Stat strip — item 1 label',                                 'Cancer rehabilitation qualified'),
  ('stat_2_label',              'Stat strip — item 2 label',                                 'Private one-to-one sessions only'),
  ('stat_3_label',              'Stat strip — item 3 label',                                 'Free, no-pressure consultation'),
  ('stat_4_label',              'Stat strip — item 4 label',                                 'Private studio, West Sussex'),
  ('faq_eyebrow',               'FAQ — eyebrow',                                             'Common Questions'),
  ('faq_heading',               'FAQ — heading',                                             'Common Questions About Cancer Rehabilitation'),
  ('faq_intro',                 'FAQ — intro',                                               'If your question is not covered here, just ask — I would always rather you did.'),
  ('faq_1_title',               'FAQ 1 — question',                                          'Is it safe to exercise during cancer treatment?'),
  ('faq_1_body',                'FAQ 1 — answer',                                            'Evidence now strongly supports exercise during cancer treatment — at the right intensity and with the right guidance. The programme must account for your specific treatment, side effects, and current capacity. I will always ask for GP or oncologist sign-off before beginning.'),
  ('faq_2_title',               'FAQ 2 — question',                                          'What is cancer-related fatigue and how do you account for it?'),
  ('faq_2_body',                'FAQ 2 — answer',                                            'Cancer-related fatigue (CRF) is physiologically different from ordinary tiredness — it does not improve with rest in the same way. I am trained to recognise CRF and programme around it. Sessions may be shorter or lower in intensity on harder days. That is not failure — it is appropriate clinical management.'),
  ('faq_3_title',               'FAQ 3 — question',                                          'When can I start exercising after surgery?'),
  ('faq_3_body',                'FAQ 3 — answer',                                            'This depends entirely on the type of surgery and your recovery. I work with the guidance of your surgical team and will not progress any movement without appropriate medical clearance.'),
  ('faq_4_title',               'FAQ 4 — question',                                          'Do you work with people during active treatment?'),
  ('faq_4_body',                'FAQ 4 — answer',                                            'Yes. I work with people during active chemotherapy or radiotherapy, people in remission, and those who have finished treatment but are rebuilding. Each stage requires a different approach — the programme is built around where you are right now.'),
  ('cta_heading',               'CTA — heading',                                             'Ready to find out if this is right for you?'),
  ('cta_body',                  'CTA — body paragraph',                                      'The first conversation is free, with no commitment. I work with a small number of clients at a time — so every person gets my full attention.'),
  ('cta_btn_primary',           'CTA — primary button',                                      'Book a Free Consultation'),
  ('cta_btn_secondary',         'CTA — secondary button',                                    'Call: 07517 658 128')
) AS v(block_key, label, content)
WHERE NOT EXISTS (SELECT 1 FROM page_content_blocks WHERE page_slug = 'cancer-rehabilitation' AND block_key = v.block_key);

-- PRICING page
INSERT INTO page_content_blocks (page_slug, block_key, label, content)
SELECT 'pricing', v.block_key, v.label, v.content
FROM (VALUES
  ('hero_eyebrow',              'Hero — eyebrow',                                            'Pricing'),
  ('hero_heading',              'Hero — heading',                                            'Straightforward pricing. No contracts. No surprises.'),
  ('hero_subhead',              'Hero — subheading',                                         'My pricing reflects premium 1:1 support, tailored programming, and accountability that helps you build long-term results. I start with a free consultation so you only invest in what you actually need.'),
  ('hero_btn_primary',          'Hero — primary CTA button',                                 'Book a Free Consultation'),
  ('hero_btn_secondary',        'Hero — secondary CTA link',                                 'See Pricing'),
  ('badge_label',               'Hero — badge label',                                        'Private Training'),
  ('badge_sublabel',            'Hero — badge sublabel',                                     '60-minute sessions in Worthing'),
  ('value_eyebrow',             'What You Are Investing In — eyebrow',                       'What You Are Investing In'),
  ('value_heading',             'What You Are Investing In — heading',                       'This is not a gym membership'),
  ('vp_1_title',                'Value prop 1 — title',                                      'One person. One trainer. One focus.'),
  ('vp_1_desc',                 'Value prop 1 — description',                                'Your health is not a short-term purchase — it is a long-term investment in your energy, confidence, and overall quality of life. Prioritising wellness now pays dividends for years to come.'),
  ('vp_2_title',                'Value prop 2 — title',                                      'Qualified to work where others cannot'),
  ('vp_2_desc',                 'Value prop 2 — description',                                'My pricing reflects personalised coaching focused on real, sustainable change — not quick fixes. You are paying for private sessions, tailored programmes, and expert guidance designed around your goals.'),
  ('vp_3_title',                'Value prop 3 — title',                                      'The first conversation is always free'),
  ('vp_3_desc',                 'Value prop 3 — description',                                'Most importantly, you are investing in a process that develops strength, consistency, and lasting habits. After your consultation, I will recommend the right level of support to help you progress safely and effectively.'),
  ('pricing_eyebrow',           'Pricing — eyebrow',                                         'Pricing'),
  ('pricing_heading',           'Pricing — heading',                                         'Choose what works for you'),
  ('pricing_intro',             'Pricing — intro',                                           'All sessions are 60 minutes, one-to-one, in a private studio in Worthing.'),
  ('plan_2_popular',            'Plan — most popular badge',                                 'Most Popular'),
  ('plan_1_name',               'Plan 1 — name',                                             'Single Session'),
  ('plan_1_desc',               'Plan 1 — description',                                      'Pay as you go. Ideal if you want to try a session before committing to a block.'),
  ('plan_1_cta',                'Plan 1 — CTA',                                              'Book a Free Consultation First'),
  ('plan_1_feat_1',             'Plan 1 — feature 1',                                        '60-minute one-to-one session'),
  ('plan_1_feat_2',             'Plan 1 — feature 2',                                        'Programme adapted to your needs'),
  ('plan_1_feat_3',             'Plan 1 — feature 3',                                        'Private studio in Worthing'),
  ('plan_1_feat_4',             'Plan 1 — feature 4',                                        'Full health and mobility assessment on first visit'),
  ('plan_2_name',               'Plan 2 — name',                                             'Block of 12'),
  ('plan_2_desc',               'Plan 2 — description',                                      'The most popular choice. Enough sessions to build real momentum and see meaningful change.'),
  ('plan_2_cta',                'Plan 2 — CTA',                                              'Book a Free Consultation'),
  ('plan_2_feat_1',             'Plan 2 — feature 1',                                        '12 x 60-minute sessions'),
  ('plan_2_feat_2',             'Plan 2 — feature 2',                                        'Save £5 per session vs pay-as-you-go'),
  ('plan_2_feat_3',             'Plan 2 — feature 3',                                        'Programme review and adjustment included'),
  ('plan_2_feat_4',             'Plan 2 — feature 4',                                        'Private studio in Worthing'),
  ('plan_2_feat_5',             'Plan 2 — feature 5',                                        'Sessions used at your pace — no expiry pressure'),
  ('plan_3_name',               'Plan 3 — name',                                             'Block of 24'),
  ('plan_3_desc',               'Plan 3 — description',                                      'Best value. For clients committed to long-term progress with complex or ongoing health needs.'),
  ('plan_3_cta',                'Plan 3 — CTA',                                              'Book a Free Consultation'),
  ('plan_3_feat_1',             'Plan 3 — feature 1',                                        '24 x 60-minute sessions'),
  ('plan_3_feat_2',             'Plan 3 — feature 2',                                        'Save £10 per session vs pay-as-you-go'),
  ('plan_3_feat_3',             'Plan 3 — feature 3',                                        'Ongoing programme management'),
  ('plan_3_feat_4',             'Plan 3 — feature 4',                                        'Priority scheduling'),
  ('plan_3_feat_5',             'Plan 3 — feature 5',                                        'Private studio in Worthing'),
  ('pricing_note_bold',         'Pricing note — bold',                                       'Not sure which to choose?'),
  ('pricing_note_body',         'Pricing note — body',                                       'Start with the free consultation. I will give you an honest recommendation based on your situation — not the most expensive option.'),
  ('pricing_link_areas',        'Pricing — link to specialist areas',                        'See my specialist areas'),
  ('pricing_link_faqs',         'Pricing — link to FAQs',                                    'Read the FAQs'),
  ('cta_heading',               'CTA — heading',                                             'Ready to find out if this is right for you?'),
  ('cta_body',                  'CTA — body paragraph',                                      'The first conversation is free, with no commitment. I work with a small number of clients at a time — so every person gets my full attention.'),
  ('cta_btn_primary',           'CTA — primary button',                                      'Book a Free Consultation'),
  ('cta_btn_secondary',         'CTA — secondary button',                                    'Call: 07517 658 128')
) AS v(block_key, label, content)
WHERE NOT EXISTS (SELECT 1 FROM page_content_blocks WHERE page_slug = 'pricing' AND block_key = v.block_key);

-- FAQS page
INSERT INTO page_content_blocks (page_slug, block_key, label, content)
SELECT 'faqs', v.block_key, v.label, v.content
FROM (VALUES
  ('hero_eyebrow',              'Hero — eyebrow',                                            'FAQs'),
  ('hero_heading',              'Hero — heading',                                            'Frequently Asked Questions'),
  ('hero_subhead',              'Hero — subheading',                                         'If something is stopping you from getting in touch, the answer is probably here. And if it is not — just ask.'),
  ('hero_btn_primary',          'Hero — primary CTA button',                                 'Book a Free Consultation'),
  ('hero_btn_secondary',        'Hero — secondary CTA link',                                 'Read the FAQs'),
  ('badge_label',               'Hero — badge label',                                        'No question too small'),
  ('badge_sublabel',            'Hero — badge sublabel',                                     'Just ask — I would rather you did'),
  ('sidebar_eyebrow',           'Sidebar — eyebrow',                                         'Your Questions Answered'),
  ('sidebar_heading',           'Sidebar — heading',                                         'No question is too complicated'),
  ('sidebar_body',              'Sidebar — body',                                            'I work with people whose situations are rarely straightforward. If you are wondering whether your health, disability, or circumstances make you a difficult client — they almost certainly do not.'),
  ('sidebar_jump_label',        'Sidebar — jump label',                                      'Jump to'),
  ('sidebar_btn',               'Sidebar — CTA button',                                      'Book a Free Consultation'),
  ('group_1_name',              'Group 1 — name',                                            'Getting Started'),
  ('faq_1_1_q',                 'FAQ 1.1 — question',                                        'Do I need to be fit or healthy to start?'),
  ('faq_1_1_a',                 'FAQ 1.1 — answer',                                          'No. In fact, most of my clients start from a point where conventional fitness feels inaccessible. You do not need to have exercised before, you do not need to be at a particular weight, and you do not need to be healthy in the conventional sense. The only starting point is where you are right now.'),
  ('faq_1_2_q',                 'FAQ 1.2 — question',                                        'I have never used a personal trainer before. What can I expect?'),
  ('faq_1_2_a',                 'FAQ 1.2 — answer',                                          'Everything begins with a free consultation — a relaxed conversation about what you want to achieve and what your body is currently dealing with. There is no pressure and no commitment required. From there, I will design a programme specifically for you and walk you through every exercise at a pace that feels comfortable.'),
  ('faq_1_3_q',                 'FAQ 1.3 — question',                                        'How often should I train?'),
  ('faq_1_3_a',                 'FAQ 1.3 — answer',                                          'For most clients, two sessions per week is a good starting point. For those managing health conditions or recovering from illness, one session per week may be more appropriate initially. I will recommend a frequency that is sustainable and effective for your specific situation — never more than your body can handle.'),
  ('faq_1_4_q',                 'FAQ 1.4 — question',                                        'Where are sessions held?'),
  ('faq_1_4_a',                 'FAQ 1.4 — answer',                                          'Sessions take place in a private studio in Worthing, West Sussex. The studio is used exclusively for one-to-one training — there is no public gym floor, no other clients present, and no waiting around. The address is confirmed at the point of booking.'),
  ('group_2_name',              'Group 2 — name',                                            'Health Conditions & Complex Needs'),
  ('faq_2_1_q',                 'FAQ 2.1 — question',                                        'I have cancer or am going through cancer treatment. Can you still work with me?'),
  ('faq_2_1_a',                 'FAQ 2.1 — answer',                                          'Yes. I hold a specialist qualification in cancer rehabilitation and have experience working with clients at all stages — during active treatment, in remission, and in long-term recovery. Exercise has a significant evidence base for supporting people through cancer and its treatment. I work closely with your medical team where appropriate and adapt every session to what your body can manage that day.'),
  ('faq_2_2_q',                 'FAQ 2.2 — question',                                        'I have a chronic health condition. Can personal training still help me?'),
  ('faq_2_2_a',                 'FAQ 2.2 — answer',                                          'Almost certainly yes. I am qualified in exercise referral, which means I am specifically trained to work with people who have clinical health conditions — including heart conditions, diabetes, autoimmune conditions, fibromyalgia, ME/CFS, and many others. Every programme is adapted to what your body can manage, and adjusted regularly as your health changes.'),
  ('faq_2_3_q',                 'FAQ 2.3 — question',                                        'I have a disability. Can I still do personal training?'),
  ('faq_2_3_a',                 'FAQ 2.3 — answer',                                          'Yes. I have experience working with clients with a wide range of physical disabilities and mobility limitations. Programmes are fully adaptive. If you use a wheelchair or have very limited mobility, that is the starting point — not a barrier. Please get in touch to discuss your specific situation.'),
  ('faq_2_4_q',                 'FAQ 2.4 — question',                                        'I have extremely limited mobility. Is there still something I can do?'),
  ('faq_2_4_a',                 'FAQ 2.4 — answer',                                          'Yes. My approach is to start from where you are, whatever that looks like. Some clients begin with very gentle seated exercises, breathing work, or small range-of-motion movements. Progress looks different for everyone and is always measured against your own baseline — not anyone else''s.'),
  ('faq_2_5_q',                 'FAQ 2.5 — question',                                        'I am visually impaired or blind. Can you work with me?'),
  ('faq_2_5_a',                 'FAQ 2.5 — answer',                                          'Yes. I have experience working with visually impaired clients. All exercises are adapted and described verbally in full detail, with complete awareness of sensory needs throughout every session. Please get in touch to discuss your specific situation.'),
  ('faq_2_6_q',                 'FAQ 2.6 — question',                                        'My GP has referred me for exercise. Can you help?'),
  ('faq_2_6_a',                 'FAQ 2.6 — answer',                                          'Yes. I am qualified in exercise referral and experienced in working alongside medical guidance. If you have been referred through a GP exercise scheme or have a recommendation from your doctor, I can work directly with that guidance and liaise with your healthcare team where useful.'),
  ('faq_2_7_q',                 'FAQ 2.7 — question',                                        'I have an injury. Is it safe to exercise?'),
  ('faq_2_7_a',                 'FAQ 2.7 — answer',                                          'In most cases yes, though it depends on the injury and the stage of recovery. I always start with an assessment and will not take on a client if I believe exercise would be harmful. For recent injuries or post-surgical clients, I work within the guidance of physiotherapists and medical teams.'),
  ('group_3_name',              'Group 3 — name',                                            'Inclusive Training'),
  ('faq_3_1_q',                 'FAQ 3.1 — question',                                        'Do you work with trans and non-binary clients?'),
  ('faq_3_1_a',                 'FAQ 3.1 — answer',                                          'Yes, without reservation. I work with clients across the full spectrum of gender identity and expression. You will be addressed and supported in whatever way feels right for you. If you have specific physical goals related to your gender identity, I will work with you on those without judgement.'),
  ('faq_3_2_q',                 'FAQ 3.2 — question',                                        'I have always felt uncomfortable or unwelcome in fitness spaces. Is this different?'),
  ('faq_3_2_a',                 'FAQ 3.2 — answer',                                          'This is the most common thing I hear. The private studio, the one-to-one format, and the complete absence of any mirror-and-performance culture is specifically designed to make it different. There is no dress code, no weigh-in, and no expectation of what fitness should look like. Many of my clients come to me having had negative experiences elsewhere. Most of them stay for years.'),
  ('group_4_name',              'Group 4 — name',                                            'Practicalities'),
  ('faq_4_1_q',                 'FAQ 4.1 — question',                                        'Do you offer short-term programmes?'),
  ('faq_4_1_a',                 'FAQ 4.1 — answer',                                          'Yes. While I believe in the long-term approach, I offer flexible options to suit different needs and budgets. I will recommend what I think is realistic for your goals during the initial consultation.'),
  ('faq_4_2_q',                 'FAQ 4.2 — question',                                        'What if my health changes during a programme?'),
  ('faq_4_2_a',                 'FAQ 4.2 — answer',                                          'This is something I am specifically trained to manage. If your health changes — whether that is a new diagnosis, a flare-up, a change in medication, or simply a difficult period — your programme changes with it. You do not lose sessions and you do not fall behind. You just adapt.'),
  ('faq_4_3_q',                 'FAQ 4.3 — question',                                        'Can I bring someone with me to sessions?'),
  ('faq_4_3_a',                 'FAQ 4.3 — answer',                                          'If having a carer, family member, or support person present would make you more comfortable, please let me know. I will accommodate wherever possible.'),
  ('faq_4_4_q',                 'FAQ 4.4 — question',                                        'My question is not answered here. What should I do?'),
  ('faq_4_4_a',                 'FAQ 4.4 — answer',                                          'Just get in touch. There is no question too small or too complicated. I would always rather speak to someone who is not sure than have them talk themselves out of trying.'),
  ('cta_heading',               'CTA — heading',                                             'Ready to find out if this is right for you?'),
  ('cta_body',                  'CTA — body paragraph',                                      'The first conversation is free, with no commitment. I work with a small number of clients at a time — so every person gets my full attention.'),
  ('cta_btn_primary',           'CTA — primary button',                                      'Book a Free Consultation'),
  ('cta_btn_secondary',         'CTA — secondary button',                                    'Call: 07517 658 128')
) AS v(block_key, label, content)
WHERE NOT EXISTS (SELECT 1 FROM page_content_blocks WHERE page_slug = 'faqs' AND block_key = v.block_key);

-- CONTACT page
INSERT INTO page_content_blocks (page_slug, block_key, label, content)
SELECT 'contact', v.block_key, v.label, v.content
FROM (VALUES
  ('hero_eyebrow',              'Hero — eyebrow',                                            'Contact'),
  ('hero_heading',              'Hero — heading',                                            'Get in Touch'),
  ('hero_subhead',              'Hero — subheading',                                         'Whether you have a question, want to learn more, or are ready to book your free consultation — I would love to hear from you.'),
  ('hero_btn_primary',          'Hero — primary CTA button',                                 'Send a Message'),
  ('hero_btn_secondary',        'Hero — secondary CTA link',                                 'Find the Studio'),
  ('badge_value',               'Hero — badge value',                                        'Free'),
  ('badge_label',               'Hero — badge label',                                        'First conversation'),
  ('badge_sublabel',            'Hero — badge sublabel',                                     'No pressure, no commitment'),
  ('form_eyebrow',              'Contact form — eyebrow',                                    'Contact'),
  ('form_heading',              'Contact form — heading',                                    'Send Me a Message'),
  ('form_firstname_label',      'Contact form — first name label',                           'First Name'),
  ('form_lastname_label',       'Contact form — last name label',                            'Last Name'),
  ('form_email_label',          'Contact form — email label',                                'Email'),
  ('form_phone_label',          'Contact form — phone label',                                'Phone'),
  ('form_message_label',        'Contact form — message label',                              'Message'),
  ('form_submit_btn',           'Contact form — submit button',                              'Send Message'),
  ('info_phone_heading',        'Contact info — phone heading',                              'Phone'),
  ('info_email_heading',        'Contact info — email heading',                              'Email'),
  ('info_location_heading',     'Contact info — location heading',                           'Studio Location'),
  ('info_location_body',        'Contact info — location body',                              'Worthing, West Sussex'),
  ('info_location_note',        'Contact info — location note',                              'Exact address shared after booking confirmation.'),
  ('help_heading',              'Not sure where to start — heading',                         'Not Sure Where to Start?'),
  ('help_body',                 'Not sure where to start — body',                            'That is completely normal. Send me a message or give me a call and we can have an informal chat — no pressure, no commitment. I will help you figure out whether personal training is the right next step.'),
  ('help_cta',                  'Not sure where to start — CTA',                             'Call me now'),
  ('social_heading',            'Social — heading',                                          'Follow Me'),
  ('map_eyebrow',               'Map — eyebrow',                                             'Location'),
  ('map_heading',               'Map — heading',                                             'Find the Studio'),
  ('map_intro',                 'Map — intro',                                               'Based in Worthing, West Sussex. The private studio is easily accessible by car and public transport.'),
  ('cta_heading',               'CTA — heading',                                             'Ready to find out if this is right for you?'),
  ('cta_body',                  'CTA — body paragraph',                                      'The first conversation is free, with no commitment. I work with a small number of clients at a time — so every person gets my full attention.'),
  ('cta_btn_primary',           'CTA — primary button',                                      'Send a Message'),
  ('cta_btn_secondary',         'CTA — secondary button',                                    'Call: 07517 658 128')
) AS v(block_key, label, content)
WHERE NOT EXISTS (SELECT 1 FROM page_content_blocks WHERE page_slug = 'contact' AND block_key = v.block_key);
