-- Replace the DUMMY Terms & Conditions seed with Eternal Fitness's real
-- Personal Training Agreement (Craig's 2026 contract). Dual-signed (client +
-- trainer). Updates the existing 'terms' template in place.

UPDATE document_templates SET
  name = 'Personal Training Agreement',
  requires_client_signature = true,
  requires_trainer_signature = true,
  version = 2,
  updated_at = NOW(),
  body = $json$
{
  "intro": "<p>This agreement is between <strong>Eternal Fitness</strong> (the Trainer) and the client named on this record. By signing you confirm that you have read, understood, and agreed to all terms.</p>",
  "sections": [
    { "id": "parties", "title": "A. Parties to this agreement", "html": "<p>This agreement is between the <strong>Client</strong> (as named and recorded on their Eternal Fitness client record) and the <strong>Trainer</strong>, Esther Fair, trading as Eternal Fitness. The agreement start date is the date of signing below.</p>" },
    { "id": "trainer-commitments", "title": "1. The trainer's commitments to you", "html": "<p><strong>1.1 Professional standards.</strong> The trainer will deliver all sessions professionally, in accordance with their qualifications, current industry guidelines, and within their scope of practice.</p><p><strong>1.2 Insurance.</strong> The trainer will maintain current, valid professional liability insurance throughout the duration of this agreement. Sessions will only be delivered whilst valid insurance is in place. The client will be notified of any change to the trainer's insurance status.</p><p><strong>1.3 Programme design.</strong> The trainer will design a programme based on the client's stated goals, health screening information, and assessment results, reviewed and updated regularly in response to progress and any changes to health or circumstances.</p><p><strong>1.4 Confidentiality.</strong> All personal, medical, and training information will be held in strict confidence and stored securely in accordance with UK data protection legislation (UK GDPR / Data Protection Act 2018). Information will not be shared with third parties without the client's written consent, except where required by law or to protect the client's safety.</p><p><strong>1.5 Referral.</strong> The trainer will work within their scope of practice at all times. Where medical or specialist referral is required, this will be recommended promptly. Where a condition requires medical clearance before exercise, no sessions will commence or continue until that clearance has been received in writing.</p><p><strong>1.6 Cancellation by the trainer.</strong></p><ul><li>Sessions cancelled by the trainer with less than 24 hours notice will be rescheduled at no cost or credited to the client's account.</li><li>If the trainer is late to start a session, the full session duration will be delivered or the shortfall credited.</li></ul>" },
    { "id": "client-responsibilities", "title": "2. The client's responsibilities", "html": "<p><strong>2.1 Health disclosure.</strong> The client agrees to disclose all relevant health information on the PAR-Q before their first session, including all medical conditions, diagnosed conditions, injuries, implanted medical devices, and all prescription medications. The client agrees to update the trainer immediately — before their next session — if any of the following occur:</p><ul><li>A new medical diagnosis is received</li><li>A new medication is prescribed or an existing medication is changed or stopped</li><li>A hospital admission or surgical procedure takes place</li><li>A medical professional gives new exercise restrictions or advice</li><li>Any implanted medical device is fitted, adjusted, or removed</li><li>Any significant change in physical or mental health occurs</li></ul><p><em>Withholding or providing inaccurate health information may put the client's safety at risk. Where a client fails to disclose relevant health information and this contributes to injury or adverse outcome, responsibility rests with the client.</em></p><p><strong>2.2 Medical clearance.</strong> Where the trainer determines that medical clearance is required, the client agrees to seek that clearance from their GP or relevant specialist. No sessions will be delivered until clearance has been received in writing by the trainer. Verbal clearance is not sufficient.</p><p><strong>2.3 Conduct during sessions.</strong> The client agrees to inform the trainer immediately if they experience any pain, dizziness, chest discomfort, nausea, or any unusual symptom during a session, and to follow the trainer's safety instructions at all times.</p><p><strong>2.4 Cancellation by the client.</strong></p><ul><li>Sessions must be cancelled or rescheduled with at least 24 hours notice. Sessions cancelled with less than 24 hours notice will be forfeited.</li><li>If the client is late to a session, the session will end at the scheduled time unless alternative arrangements have been agreed in advance.</li><li>All sessions are 60 minutes unless otherwise agreed in writing.</li></ul><p><strong>2.5 Independent training.</strong> Where the trainer provides a home exercise programme, the client is responsible for their own safety during independent training and agrees to inform the trainer of any difficulties, pain, or concerns.</p>" },
    { "id": "medical-clearance", "title": "3. Medical clearance requirements", "html": "<p>The following conditions automatically require written GP or specialist clearance before any sessions are delivered. This list is not exhaustive — the trainer reserves the right to request clearance for any condition deemed relevant to the client's safety. Verbal clearance is not sufficient.</p><table><thead><tr><th>Condition or medication</th><th>Clearance required from</th></tr></thead><tbody><tr><td>Any implanted medical device (pacemaker, shunt, neurostimulator, insulin pump, defibrillator)</td><td>Neurosurgeon or implanting specialist</td></tr><tr><td>Anticoagulant medication (Warfarin, Apixaban, Rivaroxaban, Dabigatran, Clopidogrel)</td><td>GP or haematologist</td></tr><tr><td>Blood disorder (polycythaemia rubra vera, haemophilia, thrombocytopenia, leukaemia)</td><td>Haematologist</td></tr><tr><td>Significant cardiac condition (heart attack, heart failure, arrhythmia, valve disease)</td><td>Cardiologist or GP</td></tr><tr><td>Uncontrolled hypertension (systolic above 180 or diastolic above 110)</td><td>GP</td></tr><tr><td>Neurological condition affecting balance, coordination, or sensation</td><td>Neurologist or GP</td></tr><tr><td>Recent surgery within 12 weeks</td><td>Surgeon or GP</td></tr><tr><td>Active cancer or cancer treatment</td><td>Oncologist or GP</td></tr><tr><td>Type 1 diabetes</td><td>GP or endocrinologist</td></tr><tr><td>Epilepsy not fully controlled by medication</td><td>Neurologist or GP</td></tr><tr><td>Any condition where a medical professional has given specific exercise restrictions</td><td>GP or relevant specialist</td></tr><tr><td>Significant respiratory condition (COPD, severe asthma, pulmonary fibrosis)</td><td>GP or respiratory specialist</td></tr></tbody></table>" },
    { "id": "payment", "title": "4. Payment terms", "html": "<p><strong>4.1 Session packages.</strong></p><ul><li>A block of 12 personal training sessions is valid for 120 days from the date of purchase.</li><li>A block of 24 personal training sessions is valid for 240 days from the date of purchase.</li><li>Sessions not used within the validity period are forfeited without refund.</li><li>Full payment is required before the block commences. No sessions will be delivered without prior payment.</li><li>A non-refundable deposit of £100 is required to secure time slots, deductible from the total cost of the first block.</li></ul><p><strong>4.2 Rolling monthly contracts.</strong></p><ul><li>Rolling contracts are subject to a minimum initial term of 3 months (12 weeks).</li><li>Cancellation within the initial 3-month term will result in the client remaining liable for the full cost of sessions in the remaining term.</li><li>After the initial 3-month term, one calendar month's written notice is required to cancel.</li><li>Monthly payments are due every 4 weeks and must be set up in advance. No sessions will be delivered if payment is outstanding.</li></ul><p><strong>4.3 Refunds.</strong> No refunds will be issued for unused sessions for any reason, including relocation, illness, change of circumstances, or voluntary withdrawal from the programme.</p><p><strong>4.4 Medical suspension.</strong> Where a client is unable to train due to a medical condition or injury, sessions may be suspended at the trainer's discretion. Suspended sessions will be held on account and used once the client has received appropriate medical clearance to resume. Sessions will not be refunded but may be rescheduled within a timeframe agreed between both parties.</p>" },
    { "id": "risk-liability", "title": "5. Risk, liability, and safety", "html": "<p><strong>5.1 Inherent risks of exercise.</strong> The client acknowledges that physical exercise carries inherent risks including musculoskeletal injury, cardiovascular events, falls, and exacerbation of existing medical conditions. The trainer will take all reasonable steps to minimise these risks through appropriate programme design and professional supervision.</p><p><strong>5.2 Client responsibility for disclosed information.</strong> The trainer's ability to ensure the client's safety depends entirely on the accuracy and completeness of information disclosed. Where a client fails to disclose relevant health information and this contributes to injury or adverse outcome, responsibility rests with the client.</p><p><strong>5.3 Scope of practice.</strong> The trainer is a qualified fitness professional and is not a medical professional, physiotherapist, dietitian, or mental health practitioner. Nothing provided constitutes medical advice, diagnosis, or treatment.</p><p><strong>5.4 Trainer liability.</strong> The trainer's liability is limited to direct loss caused by the trainer's negligence in delivering sessions. The trainer accepts no liability for:</p><ul><li>Injury resulting from the client's failure to disclose relevant health information</li><li>Injury sustained during independent training outside of supervised sessions</li><li>Loss of earnings, indirect losses, or consequential losses of any kind</li><li>Pre-existing conditions aggravated by exercise where the trainer was not informed</li></ul><p><strong>5.5 Emergency protocol.</strong> In the event of a medical emergency during a session, the trainer will call emergency services (999) immediately and administer first aid in accordance with their qualifications. The client consents to emergency services being called on their behalf in the event of a medical emergency.</p>" },
    { "id": "data-protection", "title": "6. Data protection and privacy", "html": "<p><strong>6.1 Data held.</strong> The trainer holds: name, contact details, date of birth, health screening information, medical clearance letters, session records, and payment records.</p><p><strong>6.2 Purpose and retention.</strong> This information is used solely for the purpose of delivering personal training services safely and professionally. Client records will be retained for a minimum of 7 years following the end of the training relationship, then securely destroyed.</p><p><strong>6.3 Access.</strong> The client has the right to request access to their personal data at any time. Requests should be made in writing and will be responded to within 30 days.</p>" },
    { "id": "general", "title": "7. General terms", "html": "<p><strong>7.1 Entire agreement.</strong> This agreement, together with the completed PAR-Q, constitutes the entire agreement between the trainer and the client and supersedes all previous agreements, verbal or written.</p><p><strong>7.2 Amendments.</strong> Any changes to this agreement must be agreed and signed in writing by both parties before taking effect.</p><p><strong>7.3 Governing law.</strong> This agreement is governed by the laws of England and Wales.</p><p><strong>7.4 Communication.</strong> Formal notices must be sent by email to the addresses on file. Day-to-day communication may be by text or messaging platforms as agreed between both parties.</p>" },
    { "id": "declaration", "title": "8. Declaration", "html": "<p>By signing below, both parties confirm that they have read and understood this agreement in full. The client confirms that they have completed the PAR-Q honestly and accept all terms set out in this agreement. The client confirms specifically that:</p><ul><li>They have disclosed all relevant medical conditions, medications, and health information on the PAR-Q</li><li>They understand that medical clearance may be required before sessions begin and that sessions will not commence until that clearance is received in writing</li><li>They will inform the trainer immediately of any change to their health, medication, or medical advice before their next session</li><li>They understand the risks of exercise as described in Section 5 and accept personal responsibility for health information they choose not to disclose</li><li>They have not been told by any medical professional that they must not exercise — or if they have, they have disclosed this to the trainer before signing</li></ul>" }
  ]
}
$json$::jsonb
WHERE kind = 'terms';
